version: "3.7"

services:
  web:
    environment:
        FRONTEND_HTTP_PORT: "8080"
        BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:${VERSION}
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 4080:8080
  api:
    environment:
        MEMPOOL_BACKEND: "electrum"
        CORE_RPC_HOST: "172.26.0.1"
        CORE_RPC_PORT: "8332"
        CORE_RPC_USERNAME: "mynode"
        CORE_RPC_PASSWORD: "${BITCOIN_RPC_PASS}"
        ELECTRUM_HOST: "172.26.0.1"
        ELECTRUM_PORT: "50001"
        ELECTRUM_TLS: "false"
        DATABASE_ENABLED: "true"
        DATABASE_HOST: "db"
        DATABASE_DATABASE: "mempool"
        DATABASE_USERNAME: "mempool"
        DATABASE_PASSWORD: "mempool"
        STATISTICS_ENABLED: "true"
    image: mempool/backend:${VERSION}
    user: 0:0
    restart: on-failure
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - /mnt/hdd/mynode/mempool/data:/backend/cache
  db:
    environment:
        MYSQL_DATABASE: "mempool"
        MYSQL_USER: "mempool"
        MYSQL_PASSWORD: "mempool"
        MYSQL_ROOT_PASSWORD: "admin"
    image: ${MARIA_DB_IMAGE}
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - /mnt/hdd/mynode/mempool/mysql/data:/var/lib/mysql

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: "172.26.0.0/24"
        gateway: "172.26.0.1"
