masterPassword: 'thunderhub-$2b$12$IMmGa2C29byHS7TkaAzMcuptaAQgthisisgarbage' # Invalid password unless defined in account
accounts:
  - name: 'localhost'
    serverUrl: '127.0.0.1:10009'
    macaroonPath: '/home/bitcoin/.lnd/data/chain/bitcoin/mainnet/admin.macaroon'
    certificatePath: '/home/bitcoin/.lnd/tls.cert'